// Code generated by Autowire. DO NOT EDIT.

//go:generate go run github.com/dabbertorres/autowire/cmd/autowire

//go:build !wireinject
// +build !wireinject

package main

import (
	"example.com/foo"
)

// Injectors from autowire.go:

func injectFooer() foo.Fooer {
	bar := provideBar()
	return bar
}
