// Code generated by Autowire. DO NOT EDIT.

//go:generate go run github.com/dabbertorres/autowire/cmd/autowire

//go:build !wireinject
// +build !wireinject

package main

// Injectors from autowire.go:

/* blockComment returns Foo and has a /*- style doc comment */
func blockComment() *Foo {
	foo := &Foo{}
	return foo
}

// lineComment returns Bar and has a //- style doc comment
func lineComment() *Bar {
	bar := &Bar{}
	return bar
}
