// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/dabbertorres/autowire/cmd/autowire
//+build !wireinject
//go:build !wireinject

package main

// Injectors from autowire.go:

func InitializeEvent(phrase string) (Event, error) {
	message := NewMessage(phrase)
	greeter := NewGreeter(message)
	event, err := NewEvent(greeter)
	if err != nil {
		return Event{}, err
	}
	return event, nil
}
