// Code generated by Autowire. DO NOT EDIT.

//go:generate go run github.com/dabbertorres/autowire/cmd/autowire

//go:build !wireinject
// +build !wireinject

package main

// Injectors from autowire.go:

func injectedMessage(t title, lines ...string) string {
	string2 := provideMessage(lines...)
	return string2
}
