// Code generated by Autowire. DO NOT EDIT.

//go:generate go run github.com/dabbertorres/autowire/cmd/autowire

//go:build !wireinject
// +build !wireinject

package main

// Injectors from autowire.go:

func injectFoo() (Foo, error) {
	foo, err := provideFoo()
	if err != nil {
		return 0, err
	}
	return foo, nil
}
