// Code generated by Autowire. DO NOT EDIT.

//go:generate go run github.com/dabbertorres/autowire/cmd/autowire

//go:build !wireinject
// +build !wireinject

package main

// Injectors from autowire.go:

func injectFooBar() FooBar {
	foo := _wireFooValue
	fooBar := provideFooBar(foo)
	return fooBar
}

var (
	_wireFooValue = Foo(41)
)
