// Code generated by Autowire. DO NOT EDIT.

//go:generate go run github.com/dabbertorres/autowire/cmd/autowire

//go:build !wireinject
// +build !wireinject

package main

// Injectors from autowire.go:

func injectFooBar(foo Foo) FooBar {
	bar := provideBar()
	fooBar := provideFooBar(foo, bar)
	return fooBar
}
