// Code generated by Autowire. DO NOT EDIT.

//go:generate go run github.com/dabbertorres/autowire/cmd/autowire

//go:build !wireinject
// +build !wireinject

package main

import (
	"fmt"
)

// Injectors from autowire.go:

func injectStringer(s MyString) fmt.Stringer {
	return s
}
